name: Build ESP32-C6 Breath Firmware (Arduino CLI)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Board Platform
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Enable unsafe library install
        run: arduino-cli config set library.enable_unsafe_install true          

      - name: Install Libraries
        run: |
          arduino-cli lib install "WiFiManager" "WebSerial" "Sensirion I2C SCD4x" "PubSubClient" "ArduinoJson"
          arduino-cli lib install --git-url https://github.com/ESP32Async/ESPAsyncWebServer.git
          arduino-cli lib install --git-url https://github.com/ESP32Async/AsyncTCP.git        

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:adafruit_feather_esp32c6 --warnings none --build-path ./build

      - name: List build output
        run: ls -R build         
        
      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Rename firmware with version
        run: mv build/breath.ino.bin build/breath_${VERSION}.bin

      - name: Upload firmware binary
        uses: actions/upload-artifact@v4
        with:
          name: breath-firmware
          path: build/breath_${{ env.VERSION }}.bin     
